spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portal?useSSL=false&useUnicode=true&&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xinglong828
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true